2. Create a 4×4 matrix using NumPy. Perform the following operations:  
• Extract the diagonal elements 
• Replace all even numbers with 0 
• Find the index of the maximum value using argmax()

In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4],
[9,8,7,6],
[5,6,7,8],
[10,20,30,40]
])
daigonal_elements=np.diag(a)
print(daigonal_elements)
a[a%2==0]=0
print("Matrix after changes: ",a)
max_index=np.argmax(a)
print(max_index)

[ 1  8  7 40]
Matrix after changes:  [[1 0 3 0]
 [9 0 7 0]
 [5 0 7 0]
 [0 0 0 0]]
4
