3. Write a program to create two 3×3 NumPy arrays and perform 
element-wise addition, subtraction, and matrix multiplication. Display 
results with proper labels.

In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
b = np.array([[0,9,8],
[7,6,5],
[4,3,2]])
add = a+b
print("Addition: ",add)
sub = a-b
print("Subtraction: ",sub)
multiply = np.matmul(a,b)
print("Multiplication: ",multiply)

Addition:  [[ 1 11 11]
 [11 11 11]
 [11 11 11]]
Subtraction:  [[ 1 -7 -5]
 [-3 -1  1]
 [ 3  5  7]]
Multiplication:  [[ 26  30  24]
 [ 59  84  69]
 [ 92 138 114]]
